#!/bin/bash

set -ex

BASEDIR=`dirname $0`
DESTDIR="../public_html"

PDFTITLE="Гаррі Поттер та Методи Раціональності"

cd $BASEDIR

# генеруємо docbook:
asciidoctor --backend=docbook --destination-dir=. ../*.asc

# матеріалізуємо горизонтальні лінії, щоб вони пережили конвертацію в tex:
sed -i 's|<?asciidoc-hr?>|asciidoc-hr|g' *.xml

pandoc --include-in-header=font.tex --from=docbook *.xml -o hpimr.tex
# лагодимо розмір шрифту та заголовок:
sed -i "0,/documentclass/ s/documentclass\[\]{article}/documentclass\[12pt\]{book}/g" hpimr.tex
sed -i "0,/pdftitle/ s/pdftitle={.*}/pdftitle={$PDFTITLE}/g" hpimr.tex
sed -i "0,/\\\\title{/ s/\\\\title{.*}/\\\\title{$PDFTITLE}/g" hpimr.tex
# лагодимо апостроф на такий, який розуміє tex:
sed -i "s/ʼ/'/g" hpimr.tex
# лагодимо наголоси:
sed -i "s|\(.\)\\\\{stress\\\\}|\\\\'\\1|g" hpimr.tex
# робимо лінії лініями:
sed -i 's|asciidoc-hr|\\vspace{1em} \\hrule \\vspace{1em}|g' hpimr.tex
# починаємо розділи із нової сторінки:
sed -i 's/^\\section{/\\pagebreak \\vspace{3em} \\section{/' hpimr.tex

xelatex hpimr.tex
mv hpimr.pdf $DESTDIR/

pandoc --from=docbook --to=epub3 *.xml -o hpimr.epub
mv hpimr.epub $DESTDIR/
